### ISSUE TITLE
AN0004 Hardware and Software modifications: enable SWO debug output

### ISSUE THREAD

**Issue by mirakonta** [Telecom-Design/Documentation_TD_RF_Module#4]
You really can use SWO to debug and profile power consumption.

I write about it in my blog:

http://www.scoop.it/t/the-french-wireless-connection/p/4027416957/2014/09/04/how-to-enable-swo-debug-output-in-td1208-evaluation-board

**Comment by mstempin** [comment]
Thank you for the tip!

This is working for TD1202 and TD1208 modules, but not for the TD1204: its PC15 pin is used internally for selecting the accelerometer chip on the SPI bus (CS_3G).
