### ISSUE TITLE
How to configure the timers in TD1204

### ISSUE THREAD

**Issue by prabhudurai** [Telecom-Design/Documentation_TD_RF_Module#5]
i am trying to configure the timers in TD1204.but i didnot understand this function EFM_ASSERT and also i did not find anywhere in the library where this function is defined ,can anyone help me to set  the Timers(*timer this indicates pointer to timer peripheral register block ) what does it mean exactly?

void TIMER_Enable(TIMER_TypeDef *timer, bool enable)
.
  EFM_ASSERT(TIMER_REF_VALID(timer));

**Comment by loiccheminade** [comment]
To create a timer please use the scheduler. See scheduler_blink example in the SDK.

**Comment by prabhudurai** [comment]
I would like to set the timer for 3s and it will create the interrupts so LED will be turn on , so can i do this action by using scheduler if it is please suggest me some hint because the scheduler part seems to be difficult

**Comment by prabhudurai** [comment]
i am using the RX port as a button so i need to verify if the press the button for 3 sec then the timer has to excute the interrupt and led will be turned on .in order to do that do i need to use Td.timer.h library function?. or td_scheduler.h?
