### ISSUE TITLE
Sample code for TD1204

### ISSUE THREAD

**Issue by alanblu** [Telecom-Design/Documentation_TD_RF_Module#7]
Hello!
Where can I find the sample codes for this device?

Regards!

**Comment by batchris** [comment]
Hi,

i found the FULL and CORRECT procedure , thank's @disk_91 : 
https://www.disk91.com/2014/technology/internet-of-things-technology/customize-you-sigfox-td1208-with-sdk/

.../...
The first step is to register on TD website
The second step is to link your github account in the TD Website
For this, on top menu “online service” you choose “developper dashboard”
Then you login
You click on MyAcount
You click on GitHub panel
Then you add your GitHub id here
Once done, you can access to the two GitHub repository of TelcomDesign accessible following this link : https://github.com/Telecom-Design/ .

One is public and contains documentations, the second contains the example source code and libraries.

.../...

Belle Journée,
Chris.

**Comment by alanblu** [comment]
Thank you!
